version: '3.3'
services:
  bitcoind:
    # DO NOT USE THIS IMAGE EXCEPT FOR TESTING!
    image: jvstein/bitcoin-test-node:latest
    command:
      - bitcoind
      - -printtoconsole
      - -conf=/etc/bitcoin/bitcoin.conf
    volumes:
      - ./test-bitcoin.conf:/etc/bitcoin/bitcoin.conf

  exporter:
    image: jvstein/bitcoin-prometheus-exporter:latest
    build: .
    ports:
      - "9332:9332"
    environment:
      BITCOIN_RPC_HOST: bitcoind
      BITCOIN_RPC_USER: "alice"
      BITCOIN_RPC_PASSWORD: "password=123&z!=@e"
      #BITCOIN_CONF_PATH: /etc/bitcoin/bitcoin.conf
      REFRESH_SECONDS: 1
      LOG_LEVEL: "INFO"
    depends_on:
      - bitcoind
    #volumes:
    # For explicit config file path (with BITCOIN_CONF_PATH above).
    # - ./test-bitcoin.conf:/etc/bitcoin/bitcoin.conf
    # For default bitcoin config location (nobody user).
    # - ./test-bitcoin.conf:/.bitcoin/bitcoin.conf
