{
 "title": "Bitcoin",
 "tags": [ "bitcoin" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(bitcoin_uptime, instance)"
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Verification Progress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "bitcoin_verification_progress{instance=~\"$node\"}",
     "legendFormat": "Verification Progress"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "graph",
   "description": "Sent and received traffic rates",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "repeat": "node",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(bitcoin_total_bytes_sent{instance=~\"$node\"}[5m]))",
     "legendFormat": "sent"
    },
    {
     "expr": "-sum(irate(bitcoin_total_bytes_recv{instance=~\"$node\"}[10m]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Block value",
   "type": "graph",
   "description": "Value of the block transactions in BTC.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(bitcoin_latest_block_value{instance=~\"$node\"})",
     "legendFormat": "BTC"
    }
   ]
  },
  {
   "title": "Block Creation Rate",
   "type": "graph",
   "description": "Number of blocks created per day using different trailing rates.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(sum(rate(bitcoin_blocks{instance=~\"$node\"}[3h])) * 3600 * 24)",
     "legendFormat": "3h"
    },
    {
     "expr": "floor(sum(rate(bitcoin_blocks{instance=~\"$node\"}[6h])) * 3600 * 24)",
     "legendFormat": "6h"
    },
    {
     "expr": "floor(sum(rate(bitcoin_blocks{instance=~\"$node\"}[12h])) * 3600 * 24)",
     "legendFormat": "12h"
    },
    {
     "expr": "floor(sum(rate(bitcoin_blocks{instance=~\"$node\"}[7d])) * 3600 * 24)",
     "legendFormat": "7d"
    }
   ]
  },
  {
   "title": "Network Hash Rate",
   "type": "graph",
   "description": "Estimated network hashes per second",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bitcoin_hashps{instance=~\"$node\"})",
     "legendFormat": "120-blocks"
    },
    {
     "expr": "avg(bitcoin_hashps_neg1{instance=~\"$node\"})",
     "legendFormat": "last-difficulty"
    }
   ]
  },
  {
   "title": "Estimated Fee",
   "type": "graph",
   "description": "sat/byte estimated smart fee for confirmation of transactions in a given number of blocks.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 84 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bitcoin_est_smart_fee_2{instance=~\"$node\"}) * (100 * 1000 * 1000) / 1024",
     "legendFormat": "2-blocks"
    },
    {
     "expr": "avg(bitcoin_est_smart_fee_20{instance=~\"$node\"}) * (100 * 1000 * 1000) / 1024",
     "legendFormat": "20-blocks"
    },
    {
     "expr": "avg(bitcoin_est_smart_fee_3{instance=~\"$node\"}) * (100 * 1000 * 1000) / 1024",
     "legendFormat": "3-blocks"
    },
    {
     "expr": "avg(bitcoin_est_smart_fee_5{instance=~\"$node\"}) * (100 * 1000 * 1000) / 1024",
     "legendFormat": "5-blocks"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "description": "Number of peers that have been banned and the reason for the ban.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 100 },
   "repeat": "node",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(bitcoin_banned_until{instance=~\"$node\"}) by (reason)",
     "legendFormat": "ban - {{ reason }}"
    },
    {
     "expr": "sum(bitcoin_peers{instance=~\"$node\"})",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Difficulty",
   "type": "graph",
   "description": "Difficulty value",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 116 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bitcoin_difficulty{instance=~\"$node\"})",
     "legendFormat": "difficulty"
    }
   ]
  },
  {
   "title": "Chain Branches",
   "type": "graph",
   "description": "Number of tips seen in the chain.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 132 },
   "repeat": "node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(bitcoin_num_chaintips{instance=~\"$node\"})",
     "legendFormat": "tips"
    }
   ]
  },
  {
   "title": "Versions",
   "type": "graph",
   "description": "The Bitcoin protocol and server versions.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 148 },
   "repeat": "node",
   "yaxes": [
    { "format": "none", "label": "protocol version" }
   ],
   "targets": [
    {
     "expr": "avg(bitcoin_protocol_version{instance=~\"$node\"})",
     "legendFormat": "protocol"
    },
    {
     "expr": "avg(bitcoin_server_version{instance=~\"$node\"})",
     "legendFormat": "server"
    }
   ]
  }
 ]
}